name = "nexas-worker"
main = "cloudflare/worker.js"
compatibility_date = "2024-11-20"

# Replace the placeholders below with the IDs returned by
# `wrangler kv:namespace create esp_data` and
# `wrangler kv:namespace create esp_data --preview`.
[[kv_namespaces]]
binding = "ESP_DATA"
id = "772a9a79f6af47e4bf88b6af0262479a"
preview_id = "5d180e6b37e64db89637855cfcc48754"
